### ISSUE TITLE
ClientRequest assertion failure

### ISSUE THREAD

**Issue by tjmehta** [tjmehta/emitter-domain#4]
Node v4.2.1

```
actual expected
falsetrue

      false == true

      at Socket.socketOnData (_http_client.js:303:3)
      at bound (domain.js:280:14)
      at Socket.runBound (domain.js:293:12)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at Socket.<anonymous> (/Users/tjmehta/Developer/+github/dynamic-emitter-domain/index.js:67:19)
      at Socket.wrap (/Users/tjmehta/Developer/+github/dynamic-emitter-domain/lib/create-wrap.js:8:18)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

**Comment by tjmehta** [comment]
https://github.com/nodejs/node/blob/v4.2.1/lib/_http_client.js#L303
